#!/bin/bash

# AOA Voting System - Unified Deployment Script
# No CI, No Remote Backend, Just Results.

set -e
set -o pipefail

# Config
PROFILE="aoa-dev"
REGION="ap-southeast-1"
TF_DIR="terraform"
ENV_LOCAL=".env.local"
LAMBDA_SRC_DIR="aoa-voting-stack/src"
FRONTEND_SRC_DIR="aoa-voting-stack/src"

# Step Helper
print_step() {
    echo -e "\n\033[1;34m=== STEP $1 ===\033[0m"
}

# === STEP 1: TOOLS ===
print_step "1: TOOLS"
check_tool() {
    if ! command -v $1 &> /dev/null; then
        echo "ERROR: $1 missing. Install with: $2"
        exit 1
    fi
}

# Check Terraform 1.5+
if ! command -v terraform &> /dev/null; then
    echo "ERROR: terraform missing. Install with: brew install terraform"
    exit 1
fi
TF_VER=$(terraform version -json | jq -r .terraform_version)
# Robust comparison: 1.10.x is newer than 1.5.0
if printf '%s\n%s' "1.5.0" "$TF_VER" | sort -C -V; then
    echo "Terraform version $TF_VER >= 1.5.0"
else
    echo "ERROR: terraform version $TF_VER < 1.5.0. Upgrade needed."
    exit 1
fi

check_tool "aws" "curl \"https://awscli.amazonaws.com/AWSCLIV2.pkg\" -o \"AWSCLIV2.pkg\" && sudo installer -pkg AWSCLIV2.pkg -target /"
check_tool "node" "nvm install 18"
check_tool "jq" "brew install jq"
check_tool "zip" "brew install zip"
echo "All tools present."

# === STEP 2: AWS ===
print_step "2: AWS"
echo "Checking AWS identity for profile '$PROFILE'..."
ACCOUNT_ID=$(aws sts get-caller-identity --profile "$PROFILE" --query Account --output text)
if [ $? -ne 0 ]; then
    echo "ERROR: AWS identity check failed. Run 'aws configure --profile $PROFILE'"
    exit 1
fi
echo "Account ID: $ACCOUNT_ID"

# === STEP 3: BUNDLE LAMBDAS ===
print_step "3: BUNDLE"
mkdir -p aoa-voting-stack/dist

# 6 Lambdas
LAMBDAS=("generate-audit-report" "pre-signup-checker" "results" "status" "submit-vote" "toggle-window")

for name in "${LAMBDAS[@]}"; do
    dir="$LAMBDA_SRC_DIR/$name"
    zip_file="aoa-voting-stack/dist/$name.zip"
    js_file="aoa-voting-stack/dist/$name/index.js"
    
    echo "Checking $name..."
    
    # Check if bundle needed
    if [ ! -f "$zip_file" ] || [ -n "$(find "$dir" -newer "$zip_file" -print -quit)" ]; then
        echo "Building $name..."
        cd aoa-voting-stack
        # Bundling using esbuild (configured in deploy.sh logic)
        npx esbuild "src/$name/$(ls src/$name | grep .ts | head -n 1)" \
            --bundle --platform=node --target=node20 --external:@aws-sdk/* \
            --outfile="dist/$name/index.js"
        
        cd dist/$name
        zip -r "../../dist/$name.zip" index.js &>/dev/null
        cd ../../..
        echo "Zipped to $zip_file"
    else
        echo "$name up to date. Skipping."
    fi
done

# === STEP 4: BACKEND BUILD ===
print_step "4: BACKEND"
echo "Building backend..."
cd aoa-voting-stack
npm install --silent
# Just run tsc to verify types
npx tsc --noEmit
echo "Backend verified."
cd ..

# === STEP 5: INIT ===
print_step "5: INIT"
terraform -chdir=$TF_DIR init -reconfigure
echo "Terraform initialized."

# === STEP 6: APPLY ===
print_step "6: APPLY"
terraform -chdir=$TF_DIR apply -var-file=terraform.tfvars -auto-approve

# Save outputs to .env.local
echo "# Generated by go.sh" > $ENV_LOCAL
terraform -chdir=$TF_DIR output -json | jq -r 'to_entries | .[] | "\(.key | ascii_upcase)=\(.value.value)"' >> $ENV_LOCAL
echo "Outputs saved to $ENV_LOCAL"

# Load variables
source $ENV_LOCAL

# === STEP 7: SEED ===
print_step "7: SEED"
echo "Seeding participants.json..."
# Create participants.json with the required test users if it doesn't exist or is missing them
if [ ! -f participants.json ]; then
    echo "[\"juan.dela.cruz@ust.edu.ph\", \"comelec.head@ust.edu.ph\"]" > participants.json
else
    # Ensure both are in the file using jq
    tmp=$(mktemp)
    jq '. + ["juan.dela.cruz@ust.edu.ph", "comelec.head@ust.edu.ph"] | unique' participants.json > "$tmp" && mv "$tmp" participants.json
fi
aws s3 cp participants.json "s3://$PARTICIPANT_BUCKET/participants.json" --profile "$PROFILE"

echo "Setting up test users in Cognito..."
seed_user() {
    EMAIL=$1
    if ! aws cognito-idp admin-get-user --user-pool-id "$USER_POOL_ID" --username "$EMAIL" --profile "$PROFILE" &>/dev/null; then
        aws cognito-idp admin-create-user --user-pool-id "$USER_POOL_ID" --username "$EMAIL" \
            --user-attributes Name=email,Value="$EMAIL" Name=email_verified,Value=true \
            --message-action SUPPRESS --profile "$PROFILE"
        aws cognito-idp admin-set-user-password --user-pool-id "$USER_POOL_ID" --username "$EMAIL" \
            --password "TestPass123!" --permanent --profile "$PROFILE"
        echo "Created user: $EMAIL"
    else
        echo "User $EMAIL exists."
    fi
}

seed_user "juan.dela.cruz@ust.edu.ph"
seed_user "comelec.head@ust.edu.ph"

# Group
aws cognito-idp create-group --group-name "comelec-admin" --user-pool-id "$USER_POOL_ID" --profile "$PROFILE" 2>/dev/null || true
aws cognito-idp admin-add-user-to-group --user-pool-id "$USER_POOL_ID" --username "comelec.head@ust.edu.ph" --group-name "comelec-admin" --profile "$PROFILE"
echo "Admin group configured."

# === STEP 8: VERIFY ===
print_step "8: VERIFY"
echo "Testing API status..."
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL/status")
if [ "$STATUS" == "200" ]; then
    echo "API Status: 200 OK"
else
    echo "WARNING: API status returned $STATUS"
fi

echo "Verifying DynamoDB..."
aws dynamodb describe-table --table-name "$HAS_VOTED_TABLE" --profile "$PROFILE" --query 'Table.TableStatus' --output text

# === STEP 9: DONE ===
print_step "9: DONE"
echo "╔════════════════════════════════════════════════════════════╗"
echo "║            AOA VOTING BACKEND READY                        ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║ API : $API_URL"
echo "║                                                            ║"
echo "║ run ./end.sh after GA                                      ║"
echo "╚════════════════════════════════════════════════════════════╝"
